Add books model crud add tests
fh0enix/books_reader pull request #1
Opened 2023-10-13 16:19 UTC by fh0enix

Pool Request: Adding Books Model, CRUD Operations, and Tests

Description:

This pool request introduces the Books model to the project, implements Create, Read, Update, and Delete (CRUD) operations for books, and adds corresponding unit and integration tests to ensure the functionality works as expected.

Changes Made:

Added the Books model with the following attributes:

Title
Author
ISBN (International Standard Book Number)
Description
Implemented CRUD operations for the Books model in the controllers and views:

Create new books
View a list of books
View details of a book
Edit book details
Delete books
Added validations to the Books model to ensure data integrity:

Presence validation for title, author, ISBN, and description fields.
Uniqueness validation for title, ISBN, and description fields.
Numericality validation for ISBN to ensure it's an integer.
Length validation for ISBN to ensure it's 13 characters long.
Created unit tests for the Books model to validate the model's validations and associations.

Added integration tests for the Books controller to test the CRUD operations and ensure they behave correctly.

Testing:

This pool request includes a comprehensive set of unit and integration tests for the Books model and controller. The tests validate that the CRUD operations work as expected and that the model's validations are correctly implemented.

Screenshots:

![image](https://github.com/fh0enix/books_reader/assets/13628239/7de2198f-f587-438c-a5ed-7ef315ae5106)
![image](https://github.com/fh0enix/books_reader/assets/13628239/3d724f34-34de-4b2f-a975-1f05d036e7bd)

Checklist:

 Books model added with proper attributes and validations.
 CRUD operations for books fully implemented.
 Unit tests for the Books model to validate validations and associations.
 Integration tests for the Books controller to test CRUD operations.
 No errors or failures in the test suite.
Related Issues:

Closes #X (if applicable)

Reviewer:

@loqimean

2023-10-16 20:48 UTC, loqimean reviewed
і повертай подвійні кавички)

2023-10-16 20:48 UTC, loqimean commented on .rubocop.yml
> +require: rubocop-rails
```suggestion
require: rubocop-rails

```

2023-10-16 20:48 UTC, loqimean commented on spec/routing/books_routing_spec.rb
нема сенсу в цих тестах

2023-10-16 20:48 UTC, loqimean commented on spec/routing/books_routing_spec.rb
> +    it { should route(:get, '/books').to(action: :index) }
а айдішки хардкодити то взагалі не гуд

2023-10-16 20:48 UTC, loqimean commented on db/seeds.rb
> +end
```suggestion
FactoryBot.create_list(:book, 100)
```

2023-10-16 20:48 UTC, loqimean commented on db/migrate/20231012162856_create_books.rb
> +      t.text :description
нікуди не треба додати валідацію на `null`?)

2023-10-16 20:48 UTC, loqimean commented on config/initializers/filter_parameter_logging.rb
>  ]
міняй конфіг, бо ці штуки з фідсотками погана штука

2023-10-16 20:48 UTC, loqimean commented on app/views/books/_book.html.erb
> +  <% end %>
ця штука не гуд

2023-10-16 20:48 UTC, loqimean commented on app/helpers/books_helper.rb
навіщо тобі пусті файли ці? видаляй

2023-10-16 20:48 UTC, loqimean commented on app/helpers/application_helper.rb
теж

2023-10-16 20:48 UTC, loqimean commented on app/controllers/books_controller.rb
> +  end
не гуд, сетай явно інстанс змінну там, де треба

2023-10-16 20:48 UTC, loqimean commented on app/controllers/books_controller.rb
> +  before_action :set_book, only: %i[show edit update destroy]
видаляй

2023-10-16 20:48 UTC, loqimean commented on app/controllers/books_controller.rb
> +    @books = Book.all
ордеред має бути

2023-10-16 20:48 UTC, loqimean commented on app/controllers/books_controller.rb
> +  # PATCH/PUT /books/1
видаляй ці коменти

2023-10-16 20:48 UTC, loqimean commented on app/controllers/books_controller.rb
> +    @book.destroy!
а чому тут заюзаний бенг метод?

2023-10-16 20:48 UTC, loqimean commented on app/controllers/books_controller.rb
> +    redirect_to books_url, notice: 'Book was successfully destroyed.', status: :see_other
юзай `_path`

2023-10-16 20:48 UTC, loqimean commented on app/views/books/_form.html.erb
> +<%= form_with(model: book, class: "contents") do |form| %>
юзай сімпл форм

2023-10-16 20:48 UTC, loqimean commented on app/views/books/edit.html.erb
> +  <%= render "form", book: @book %>
прописуй повний шлях до паршала

2023-10-16 20:48 UTC, loqimean commented on app/views/books/edit.html.erb
> +  <%= link_to "Show this book", @book, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
задавай явно роут

2023-10-16 20:48 UTC, loqimean commented on app/views/books/index.html.erb
> +  <% end %>
а навіщо це тут? чому воно дублюється?

2023-10-16 20:48 UTC, loqimean commented on app/views/books/index.html.erb
> +    <%= render @books %>
явно вказуй шлях на рендер колекції

2023-10-16 20:48 UTC, loqimean commented on app/views/books/new.html.erb
> +  <%= render "form", book: @book %>
повний шлях до паршала

2023-10-16 20:48 UTC, loqimean commented on app/views/books/show.html.erb
> +    <% end %>
ну от знову

2023-10-16 20:48 UTC, loqimean commented on app/views/books/show.html.erb
> +    <%= render @book %>
те ж саме

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +RSpec.describe '/books', type: :request do
```suggestion
RSpec.describe BooksController, type: :request do
```

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { { title: '', author: '', isbn: '', description: '' } }
хватає одного атрибуту

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +  describe 'POST /create' do
```suggestion
  describe 'POST #create' do
```

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +          post books_url, params: { book: valid_attributes }
```suggestion
          post books_url, params: valid_params
```

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +      end
в один тест це перемісти

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +      end
і так скрізь

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(book.author).to eq(new_attributes[:author])
.to change(some, :field)

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_url(book))
в один тест

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to have_http_status(:unprocessable_entity)
be_unprocessable

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to redirect_to(books_url)
```suggestion
      delete book_url(book)

      expect(response).to redirect_to(books_url)
```

2023-10-16 20:48 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to redirect_to(books_url)
розділяй логічно строки

2023-10-17 06:25 UTC, fh0enix commented on spec/requests/books_spec.rb
> +        expect(response).to have_http_status(:unprocessable_entity)
solve

2023-10-17 06:27 UTC, fh0enix commented on db/seeds.rb
> +end
solve

2023-10-17 06:46 UTC, fh0enix commented on db/migrate/20231012162856_create_books.rb
> +      t.text :description
валідація присутня в класі моделі

2023-10-17 06:49 UTC, fh0enix commented on app/controllers/books_controller.rb
> +  # PATCH/PUT /books/1
solve

2023-10-17 06:51 UTC, fh0enix commented on app/helpers/books_helper.rb
solve

2023-10-17 08:37 UTC, fh0enix commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { { title: '', author: '', isbn: '', description: '' } }
solve

2023-10-17 08:38 UTC, fh0enix commented on spec/requests/books_spec.rb
> +  describe 'POST /create' do
solve

2023-10-17 08:41 UTC, fh0enix commented on spec/requests/books_spec.rb
> +RSpec.describe '/books', type: :request do
solved

2023-10-17 08:45 UTC, fh0enix commented on spec/requests/books_spec.rb
> +      expect(response).to redirect_to(books_url)
solved

2023-10-17 10:00 UTC, fh0enix commented on app/views/books/edit.html.erb
> +  <%= link_to "Show this book", @book, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
solved

2023-10-17 10:03 UTC, fh0enix commented on app/views/books/edit.html.erb
> +  <%= render "form", book: @book %>
solved

2023-10-17 10:05 UTC, fh0enix commented on app/views/books/new.html.erb
> +  <%= render "form", book: @book %>
solved

2023-10-17 10:44 UTC, fh0enix commented on app/views/books/show.html.erb
> +    <%= render @book %>
solved

2023-10-17 10:51 UTC, fh0enix commented on app/views/books/index.html.erb
> +  <% end %>
solved

2023-10-17 11:02 UTC, fh0enix commented on app/controllers/books_controller.rb
> +  before_action :set_book, only: %i[show edit update destroy]
solved

2023-10-17 11:12 UTC, fh0enix commented on app/controllers/books_controller.rb
> +  end
solved

2023-10-17 11:17 UTC, fh0enix commented on app/controllers/books_controller.rb
> +    @book.destroy!
solved

2023-10-17 11:17 UTC, fh0enix commented on app/controllers/books_controller.rb
> +    redirect_to books_url, notice: 'Book was successfully destroyed.', status: :see_other
solved

2023-10-17 11:17 UTC, fh0enix commented on app/controllers/books_controller.rb
> +    @books = Book.all
solved

2023-10-17 11:18 UTC, fh0enix commented on spec/routing/books_routing_spec.rb
solved

2023-10-17 11:18 UTC, fh0enix commented on spec/routing/books_routing_spec.rb
> +    it { should route(:get, '/books').to(action: :index) }
solved

2023-10-17 11:18 UTC, fh0enix commented on app/helpers/application_helper.rb
solved

2023-10-17 11:51 UTC, fh0enix commented on app/views/books/index.html.erb
> +    <%= render @books %>
solved

2023-10-17 11:52 UTC, fh0enix commented on app/views/books/show.html.erb
> +    <% end %>
solved

2023-10-17 11:55 UTC, fh0enix commented on config/initializers/filter_parameter_logging.rb
>  ]
solved

2023-10-17 12:00 UTC, fh0enix commented on app/views/books/_book.html.erb
> +  <% end %>
solved

2023-10-17 12:23 UTC, fh0enix commented on spec/requests/books_spec.rb
> +        expect(book.author).to eq(new_attributes[:author])
solved

2023-10-17 14:40 UTC, fh0enix commented on app/views/books/_form.html.erb
> +<%= form_with(model: book, class: "contents") do |form| %>
solved

2023-10-17 14:51 UTC, fh0enix commented on app/views/books/_form.html.erb
> +<%= form_with(model: book, class: "contents") do |form| %>
solved

2023-10-18 06:18 UTC, fh0enix commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_url(book))
solved

2023-10-29 14:04 UTC, loqimean requested changes

2023-10-29 14:04 UTC, loqimean commented on Gemfile
> +
```suggestion
```

2023-10-29 14:04 UTC, loqimean commented on Gemfile
> +gem "simple_form"
казав юзати мій форк, бо там є вже готові стилі для форми))

2023-10-29 14:04 UTC, loqimean commented on app/channels/application_cable/channel.rb
> +
що це за пусті строки скрізь?)

2023-10-29 14:04 UTC, loqimean commented on app/controllers/books_controller.rb
> +      flash[:notice] = "Book was successfully created."
це взагалі не гуд, бо ти зараз редіректнеш юзера і лише тоді засетаєш флеш, тобто він або не покажеться, або покажеться на наступній сторінці, де це вже і не потрібно

2023-10-29 14:04 UTC, loqimean commented on app/controllers/books_controller.rb
> +      flash[:notice] = "Book was successfully updated."
аналогічно + розділяй новою строкою

2023-10-29 14:04 UTC, loqimean commented on app/controllers/books_controller.rb
> +    flash[:alert] = "Book was successfully deleted."
це теж

2023-10-29 14:04 UTC, loqimean commented on app/helpers/application_helper.rb
повертай цей файл

2023-10-29 14:04 UTC, loqimean commented on app/models/book.rb
> +
а ця нова строка навіщо?

2023-10-29 14:04 UTC, loqimean commented on app/views/books/_form.html.erb
> +  <%= simple_form_for @book, defaults: { input_html: { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } } do |f| %>
а куда ти посилаєш цю форму? я не бачу посилання. UDP (я знаю, що посилання створюється автоматично)

2023-10-29 14:04 UTC, loqimean commented on app/views/books/index.html.erb
> +  <div id="books" class="min-w-full">
а тобі дійсно треба тут айдішка?

2023-10-29 14:04 UTC, loqimean commented on app/views/books/new.html.erb
> +  <%= link_to "BACK TO BOOKS", books_path, class: "btn-green" %>
розділяй новою строкою, буде краща читабельність

2023-10-29 14:04 UTC, loqimean commented on app/views/layouts/_footer.html.erb
а навіщо тобі пустий файл?

2023-10-29 14:04 UTC, loqimean commented on app/views/layouts/_header.html.erb
це теж

2023-10-29 14:04 UTC, loqimean commented on config/application.rb
> +    config.autoload_lib(ignore: %w[assets tasks])
такс, давай забирай цю штуку з відсотками

2023-10-29 14:04 UTC, loqimean commented on config/environment.rb
ну прям скрізь ці нові строки....

2023-10-29 14:04 UTC, loqimean commented on db/migrate/20231012162856_create_books.rb
> +      t.text :description, null: false
а тут точно треба нул фолс?

2023-10-29 14:04 UTC, loqimean commented on db/seeds.rb
> +
видаляяяй

2023-10-29 14:04 UTC, loqimean commented on spec/requests/books_spec.rb
> +    end
видаляй цей тест, з нього мало толку. Краще потестуй, що у тебе на сторінці дійсно ця книга відрендерилася

2023-10-29 14:04 UTC, loqimean commented on spec/requests/books_spec.rb
> +    end
і так скрізь

2023-10-29 14:04 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(assigns(:book)).to be_a_new(Book)
те ж саме

2023-10-29 18:54 UTC, fh0enix commented on Gemfile
> +gem "simple_form"
та то ж була рекомендація))

2023-10-29 18:58 UTC, fh0enix commented on app/channels/application_cable/channel.rb
> +
fixed

2023-10-29 19:00 UTC, fh0enix commented on app/controllers/books_controller.rb
> +      flash[:notice] = "Book was successfully updated."
fixed

2023-10-29 19:00 UTC, fh0enix commented on app/controllers/books_controller.rb
> +      flash[:notice] = "Book was successfully created."
fixed

2023-10-29 19:01 UTC, fh0enix commented on app/controllers/books_controller.rb
> +    flash[:alert] = "Book was successfully deleted."
fixed

2023-10-29 19:01 UTC, fh0enix commented on app/models/book.rb
> +
fixed

2023-10-29 19:12 UTC, fh0enix commented on app/views/books/new.html.erb
> +  <%= link_to "BACK TO BOOKS", books_path, class: "btn-green" %>
fixed

2023-10-29 19:13 UTC, fh0enix commented on app/views/layouts/_footer.html.erb
fixed

2023-10-29 19:14 UTC, fh0enix commented on app/views/layouts/_header.html.erb
fixed

2023-10-29 19:15 UTC, fh0enix commented on config/application.rb
> +    config.autoload_lib(ignore: %w[assets tasks])
fixed

2023-10-29 19:16 UTC, fh0enix commented on config/environment.rb
fixed....це після рубокопських фроузенів полишалося а я не фіксанув

2023-10-29 19:20 UTC, fh0enix commented on db/migrate/20231012162856_create_books.rb
> +      t.text :description, null: false
fixed

2023-10-29 19:47 UTC, fh0enix commented on db/seeds.rb
> +
fixed

2023-10-29 20:25 UTC, fh0enix commented on app/helpers/application_helper.rb
fixed

2023-10-29 20:48 UTC, fh0enix commented on app/views/books/_form.html.erb
> +  <%= simple_form_for @book, defaults: { input_html: { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } } do |f| %>
fixed

2023-10-30 08:15 UTC, fh0enix commented on spec/requests/books_spec.rb
> +      expect(assigns(:book)).to be_a_new(Book)
fixed

2023-10-30 08:28 UTC, fh0enix commented on spec/requests/books_spec.rb
> +    end
fixed

2023-11-01 18:12 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +  }
```suggestion
  }

```

2023-11-01 18:12 UTC, loqimean commented on app/assets/builds/tailwind.css
delete it

2023-11-01 18:12 UTC, loqimean commented on app/controllers/books_controller.rb
> +      redirect_to book_path(@book)
обʼєднай

2023-11-01 18:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
енма перевірки на присутність рекорда на сторінці

2023-11-02 11:40 UTC, fh0enix commented on app/assets/builds/tailwind.css
fixed

2023-11-02 13:00 UTC, fh0enix commented on app/controllers/books_controller.rb
> +      redirect_to book_path(@book)
solved

2023-11-02 13:12 UTC, fh0enix commented on app/assets/builds/tailwind.css
it deleted

2023-11-02 13:42 UTC, fh0enix commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
added

2023-11-02 13:43 UTC, fh0enix commented on app/assets/stylesheets/application.tailwind.css
> +  }
solved

2023-11-05 10:09 UTC, merged