Add-Devise-authentication,-Users-model,-Add-tests
fh0enix/books_reader pull request #2
Opened 2023-11-06 16:17 UTC by fh0enix

Title: Adding Devise Authentication and Users Model with Test Cases

Description:

This pull request introduces essential changes to enhance the security and user management of our application. Here's a breakdown of what this pull request accomplishes:

Devise Authentication Integration: Devise authentication has been integrated into our application. This ensures a robust and reliable user authentication system, providing a secure gateway for our users to access the platform.

Users Model Implementation: A dedicated "User" model has been introduced. This model encapsulates essential user-related data and functionalities, paving the way for efficient user management.

Comprehensive Test Suite: To maintain the reliability of our application, an extensive suite of tests has been included. These tests rigorously examine the functionality of the authentication system, ensuring that our users' data remains protected and our features operate as expected.

The integration of Devise and the introduction of the Users model significantly improve our application's security and user management. The comprehensive test coverage guarantees the stability of these changes.

Please review these modifications thoroughly, paying special attention to the security aspects and the impact on user functionality. Your feedback and suggestions are highly appreciated to ensure the successful implementation of this critical update.

Reviewer:

@loqimean

2023-11-06 21:22 UTC, loqimean requested changes

2023-11-06 21:22 UTC, loqimean commented on app/controllers/application_controller.rb
> +  #before_action :authenticate_user!
видаляй зайве

2023-11-06 21:22 UTC, loqimean commented on app/controllers/application_controller.rb
> +  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_name])
де відступи? кодстайл

2023-11-06 21:22 UTC, loqimean commented on app/models/user.rb
> +validates :first_name, :last_name, :user_name, presence: true
де відступи?

2023-11-06 21:22 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +			<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 32 32" class="w-8 h-8 dark:text-cyan-400">
`inline_svg`

2023-11-06 21:22 UTC, loqimean commented on app/views/layouts/application.html.erb
> +
```suggestion
```

2023-11-06 21:22 UTC, loqimean commented on app/views/layouts/application.html.erb
> +
```suggestion
```

2023-11-06 21:22 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +</header>
чому тут по 4 пробіли? якщо не більше. виправляй

2023-11-06 21:22 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-6 h-6 dark:text-gray-100">
`inline_svg`

2023-11-06 21:22 UTC, loqimean commented on config/routes.rb
> +  devise_for :users
тобі прям всі роути тре?

2023-11-06 21:22 UTC, loqimean commented on db/seeds.rb
> +FactoryBot.create_list(:book, 5)
а юзери?

2023-11-06 21:22 UTC, loqimean commented on spec/models/user_spec.rb
> +    it { should validate_presence_of(:email) }
це старий синтаксис. міняй

2023-11-06 21:22 UTC, loqimean commented on spec/models/user_spec.rb
> +  end
це вверх і без класу юзай

2023-11-06 21:22 UTC, loqimean commented on spec/rails_helper.rb
> +  config.include Devise::Test::ControllerHelpers, type: :controller
не в той тип передав

2023-11-06 21:22 UTC, loqimean commented on spec/requests/users_spec.rb
> +          post user_registration_path, params: { user: FactoryBot.attributes_for(:user) }
фекторі_бот клас дефайниться глобально, нема сенсу писати константу

2023-11-07 09:45 UTC, fh0enix commented on app/controllers/application_controller.rb
> +  #before_action :authenticate_user!
solved

2023-11-07 09:48 UTC, fh0enix commented on app/models/user.rb
> +validates :first_name, :last_name, :user_name, presence: true
sorry
solved

2023-11-07 10:00 UTC, fh0enix commented on app/views/layouts/application.html.erb
> +
solved

2023-11-07 10:00 UTC, fh0enix commented on app/views/layouts/application.html.erb
> +
solved

2023-11-07 10:02 UTC, fh0enix commented on config/routes.rb
> +  devise_for :users
solved

2023-11-07 10:03 UTC, fh0enix commented on db/seeds.rb
> +FactoryBot.create_list(:book, 5)
solved

2023-11-07 10:16 UTC, fh0enix commented on spec/requests/users_spec.rb
> +          post user_registration_path, params: { user: FactoryBot.attributes_for(:user) }
solved

2023-11-07 12:17 UTC, fh0enix commented on spec/models/user_spec.rb
> +  end
deleted it

2023-11-07 12:17 UTC, fh0enix commented on spec/models/user_spec.rb
> +    it { should validate_presence_of(:email) }
solved

2023-11-07 12:31 UTC, fh0enix commented on spec/rails_helper.rb
> +  config.include Devise::Test::ControllerHelpers, type: :controller
solved?

2023-11-07 12:34 UTC, fh0enix commented on app/views/layouts/_header.html.erb
> +</header>
The code містить пробіли, які відповідають HTML-відступам для кращої читабельності коду

2023-11-07 15:35 UTC, fh0enix commented on app/views/layouts/_header.html.erb
> +			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-6 h-6 dark:text-gray-100">
solved

2023-11-07 15:35 UTC, fh0enix commented on app/views/layouts/_header.html.erb
> +			<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 32 32" class="w-8 h-8 dark:text-cyan-400">
solved

2023-11-08 08:54 UTC, loqimean requested changes

2023-11-08 08:54 UTC, loqimean commented on config/routes.rb
>    root "books#index"
на верх перед девайсом

2023-11-08 08:54 UTC, loqimean commented on config/routes.rb
> +  devise_for :users, only: [:sessions, :registrations]
```suggestion
  devise_for :users, only: [:sessions, :registrations]

```

2023-11-08 08:54 UTC, loqimean commented on spec/models/user_spec.rb
> +    it { is_expected.to validate_presence_of(:user_name) }
два пробіли

2023-11-08 08:54 UTC, loqimean commented on spec/requests/users_spec.rb
> +          post user_registration_path, params: { user: FactoryBot.attributes_for(:user) }
не солвед)

2023-11-08 08:54 UTC, loqimean commented on app/controllers/application_controller.rb
> +end
два пробіли

2023-11-08 08:54 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +			<% if current_user %>
код стайл

2023-11-08 09:45 UTC, fh0enix commented on app/controllers/application_controller.rb
> +end
solved

2023-11-08 09:46 UTC, fh0enix commented on app/views/layouts/_header.html.erb
> +			<% if current_user %>
solved

2023-11-08 09:46 UTC, fh0enix commented on config/routes.rb
>    root "books#index"
solved

2023-11-08 09:47 UTC, fh0enix commented on config/routes.rb
> +  devise_for :users, only: [:sessions, :registrations]
solved

2023-11-08 09:49 UTC, fh0enix commented on spec/models/user_spec.rb
> +    it { is_expected.to validate_presence_of(:user_name) }
solved

2023-11-08 13:44 UTC, fh0enix commented on app/controllers/application_controller.rb
> +  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_name])
solved

2023-11-08 14:03 UTC, fh0enix commented on spec/requests/users_spec.rb
> +          post user_registration_path, params: { user: FactoryBot.attributes_for(:user) }
now I have desided it

2023-11-15 18:31 UTC, loqimean requested changes

2023-11-15 18:31 UTC, loqimean commented on app/views/books/_show_book.html.erb
> +				<h3 class="text-xl font-semibold dark:dark:text-gray-100"><%= book.title %></h3>
ну що це за приколи з табами по 8 пробілів?))

2023-11-15 18:31 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +				<%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "self-center px-8 py-3 font-semibold rounded dark:bg-amber-400 dark:text-gray-900" %>
та ж історія

2023-11-15 18:31 UTC, loqimean commented on config/routes.rb
> +  devise_for :users, only: [:sessions, :registrations]
```suggestion
  devise_for :users, only: [:sessions, :registrations]

  root "books#index"
```

2023-11-16 08:55 UTC, fh0enix commented on config/routes.rb
> +  devise_for :users, only: [:sessions, :registrations]
solved

2023-11-16 20:54 UTC, loqimean requested changes

2023-11-16 20:54 UTC, loqimean commented on app/views/layouts/_header.html.erb
> +      <% if current_user %>
```suggestion
      <% if current_user.present? %>
```

2023-11-16 20:54 UTC, loqimean commented on app/views/layouts/application.html.erb
> +
не солвед)

2023-11-17 08:22 UTC, fh0enix commented on app/views/layouts/application.html.erb
> +
солвед)

2023-11-17 08:27 UTC, fh0enix commented on app/views/layouts/_header.html.erb
> +      <% if current_user %>
solved

2023-11-22 08:31 UTC, loqimean approved these changes

2023-11-22 09:01 UTC, merged