Add-Active-Storage,-Add-tests
fh0enix/books_reader pull request #3
Opened 2023-11-13 20:52 UTC by fh0enix

Description:

This pull request introduces the implementation of Active Storage for handling file attachments in the  model. Additionally, comprehensive tests have been added to ensure the correct functioning of the new features.Book

Changes Made:

Active Storage Integration:

Added the necessary configuration for Active Storage in the  model.Book
Implemented the attachment of PDF files to  records using Active Storage.Book
Test Suite:

Added thorough tests to validate the behavior of Active Storage attachment.
Ensured that valid and invalid cases are covered to maintain code integrity.
Tested file uploads and their associations with the  model.Book
Files Modified:

app/models/book.rb
spec/models/book_spec.rb
spec/controllers/books_controller_spec.rb

Testing Instructions:

Create a new Book with a valid PDF attachment.
Attempt to create a Book with invalid data, ensuring it fails gracefully.
Verify that PDF attachments are correctly associated with Book records in the database.

Please review these modifications thoroughly, paying special attention to the security aspects and the impact on user functionality. Your feedback and suggestions are highly appreciated to ensure the successful implementation of this critical update.

Reviewer:

@loqimean

2023-11-15 18:37 UTC, loqimean requested changes

2023-11-15 18:37 UTC, loqimean commented on app/assets/book_test/test.pdf
стоп, а чому тестові файли зберігаються тут, а не в папці тестів??

2023-11-15 18:37 UTC, loqimean commented on app/models/book.rb
> +  has_one_attached :pdf
а якщо я видалю книгу?

2023-11-15 18:37 UTC, loqimean commented on app/views/books/_form.html.erb
> +      <%= f.input :pdf, as: :file, label: false, hint: "PDF File (up to 20MB)" %>
а де та валідація на лесс зен 20мб?))

2023-11-15 18:37 UTC, loqimean commented on spec/factories/books.rb
> +      after(:create) do |book|
а якщо я хочу зробити білд?

2023-11-15 18:37 UTC, loqimean commented on spec/factories/books.rb
> +        content_path = Rails.root.join("app", "assets", "book_test", "test.pdf")
ой не там той файл має бути....

2023-11-15 18:37 UTC, loqimean commented on spec/models/book_spec.rb
> +    book = FactoryBot.create(:book, :with_content)
ну а `let` для кого придумали?)

2023-11-15 18:37 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to render_template(:new)
щось взагалі не гуд, бо:
1. чому багатолінійний блок написаний фігурними скобками?
2. чому ти не тестує те, що от ця книга стала доступна на сторінці?

2023-11-16 16:07 UTC, fh0enix commented on app/views/books/_form.html.erb
> +      <%= f.input :pdf, as: :file, label: false, hint: "PDF File (up to 20MB)" %>
solved

2023-11-16 16:10 UTC, fh0enix commented on spec/models/book_spec.rb
> +    book = FactoryBot.create(:book, :with_content)
solved

2023-11-16 16:10 UTC, fh0enix commented on spec/factories/books.rb
> +      after(:create) do |book|
solved

2023-11-16 16:10 UTC, fh0enix commented on app/assets/book_test/test.pdf
solved

2023-11-16 20:08 UTC, fh0enix commented on spec/requests/books_spec.rb
> +        expect(response).to render_template(:new)
solved

2023-11-22 09:05 UTC, loqimean requested changes

2023-11-22 09:05 UTC, loqimean commented on app/models/book.rb
> +  end
та наче має бути вбудований спосіб валідації розміру

2023-11-22 09:05 UTC, loqimean commented on spec/factories/books.rb
> +        content_path { Rails.root.join("spec", "fixtures", "files", "test.pdf") }
spec/support/files

2023-11-22 09:05 UTC, loqimean commented on spec/factories/books.rb
> +        end
а чому після створення? давай відразу

2023-11-22 09:05 UTC, loqimean commented on spec/models/book_spec.rb
> +    expect(book.pdf.byte_size).to be < 20.megabytes
а воно взагалі так працює?))

2023-11-22 12:27 UTC, fh0enix commented on spec/factories/books.rb
> +        content_path { Rails.root.join("spec", "fixtures", "files", "test.pdf") }
fixed

2023-11-22 13:31 UTC, fh0enix commented on spec/factories/books.rb
> +        end
fixed

2023-11-22 14:23 UTC, fh0enix commented on app/models/book.rb
> +  end
з коробки не знайшов, але є гем який надає такий функціонал => gem 'active_storage_validations'

2023-11-22 14:46 UTC, fh0enix commented on spec/models/book_spec.rb
> +    expect(book.pdf.byte_size).to be < 20.megabytes
Ппрацює ....
![image](https://github.com/fh0enix/books_reader/assets/13628239/5dbeddbf-9166-4b15-bd1c-4a91b9a24c97)

2023-11-22 15:30 UTC, loqimean requested changes

2023-11-22 15:30 UTC, loqimean commented on app/models/book.rb
> +  end
ну знач його юзай)

2023-11-22 15:30 UTC, loqimean commented on spec/models/book_spec.rb
> +    expect(book.pdf.byte_size).to be < 20.megabytes
мене турбує не отримання розміру, а те, що ти робиш після експекта)

2023-11-22 16:41 UTC, fh0enix commented on app/models/book.rb
> +  end
solved

2023-11-22 16:42 UTC, fh0enix commented on spec/models/book_spec.rb
> +    expect(book.pdf.byte_size).to be < 20.megabytes
solved

2023-11-28 07:26 UTC, loqimean approved these changes

2023-11-28 09:49 UTC, merged